config/routes.rb
TravelQaParser::Application.routes.draw do
  root 'questions#index'

  resources :questions do
    get "change_marker" => "questions#change_marker"
    get "parse" => "questions#parse", on: :collection
    get "parse_ta" => "questions#parse_ta", on: :collection
    get "resume_parse" => "questions#resume_parse", on: :collection
    get "resume_parse_ta" => "questions#resume_parse_ta", on: :collection
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include EncodeGuard
  belongs_to :questions
end

app/models/concerns/encode_guard.rb
module EncodeGuard
  extend ActiveSupport::Concern

  included do
    before_save :encode_content, if: :content
  end

  def encode_content
    assign_attributes content: content.gsub(/[\xF0\x9F\x98\x80-\xF0\x9F\x99\x8F]/, '')
  end
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :forums
  validates :name, uniqueness: true
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  belongs_to :destination
  has_many :questions
  validates :url, uniqueness: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  include EncodeGuard
  
  MARKERS = ["unmarked","suitable","unsuitable","complete"].freeze

  belongs_to :forum
  has_many :answers
  validates :url, uniqueness: true
  validates :marker, inclusion: { in: MARKERS, allow_nil: true }

  before_save :record_max_strange_answer_length
  before_save :record_longest_answer_length


  def self.dedupe
    grouped = all.group_by{|model| [model.url, model.forum_id] }
    
    grouped.values.each do |duplicates|
      first_one = duplicates.shift
      duplicates.each{|double| double.destroy}
    end
  end
  
  private
  def record_longest_answer_length
    longest_answer_length = answers.pluck(:length).try(:max)
  end

  def record_max_strange_answer_length
    max_strange_answer_length = (answers.pluck(:length, :author).reject{ |e| e[1] == author}.try(:max).try(:[], 0) || 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  http_basic_authenticate_with name: "travel_admin", password: "parsertravelqa"

  def index
    # question_relation = params[:checked] # ? Question.joins(:answers).where("answers.length > ?", params[]) : Question
    if params[:q] = params[:q].presence
      params[:q][:source_null] = true if params[:q][:source_eq] == ""
    end
    
    @search = Question.search(params[:q])
    @questions = @search.result.includes(forum: :destination).uniq.paginate(page: params[:page], per_page: 100)
  end
  
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.paginate(page: params[:page], per_page: 30)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def change_marker
    @question = Question.find(params[:question_id])
    @question.update_attribute(:marker, params[:marker])
  end

  def parse
    Parser::LonleyPlanet.start_parse_async
    redirect_to root_path
  end
  def parse_ta
    Parser::TripAdvisor.start_parse_async
    redirect_to root_path

  end
  def resume_parse
    Parser::LonleyPlanet.perform_async
    redirect_to root_path
  end
  def resume_parse_ta
    Parser::TripAdvisor.perform_async
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def markers_for(question)    
    Question::MARKERS.each do |marker|
      default_btn_class = if question.marker == marker 
                            "btn btn-default btn-success disabled "
                          else
                            "btn btn-default "  
                          end << marker

      concat link_to(t(marker), 
                     question_change_marker_path(question, marker: marker), 
                     class: default_btn_class, remote: true)

    end
    
    return
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TravelQaParser" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">TravelQaParser</a>
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :title, "Заголовок", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, "Содержание", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_answers_weight, "Символов в ответах", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :total_answers_weight, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :marker, "Метка", :class => 'control-label' %>
    <div class="controls">
      <%= f.select :marker, Question::MARKERS.map { |marker| [t(marker), marker] }, include_blank: 'без метки', :class => 'form-control' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<tr id="<%= dom_id question %>">
  <td><%= question.forum.destination.name %></td>
  <td><%= question.forum.name %></td>
  <td><%= link_to question.title, question_path(question) %></td>
  <td><%= "#{question.content.try(:[], 0..140)}..." %></td>
  <td><%= question.total_answers_weight %></td>
  <td><%= question.views_count || "..." %></td>
  <td>
    <div class="btn-group-vertical btn-group-xs">
      <%= markers_for question %>
    </div>
  </td>
</tr>

app/views/questions/change_marker.js.erb
var question = $("#question_<%= params[:question_id] %>");
question.find(".disabled").removeClass("disabled").removeClass("btn-success");
question.find(".<%= params[:marker] %>").addClass("disabled").addClass("btn-success");

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1>Изменить вопрос</h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t 'Questions' %></h1>
  <!-- <%= link_to "Продолжить парсинг", resume_parse_questions_path %> -->
</div>

<div id="search">
  <h2>Поиск</h2>
  <%= search_form_for @search, class: "form-inline" do |f| %>
    <div class="form-group">
      <%= f.label :title_cont, "Тема", class: "sr-only" %>
      <%= f.text_field :title_cont, class: "form-control", placeholder: "Тема" %>
    </div>
    <div class="form-group">
      <%= f.label :forum_name_cont, "Форум", class: "sr-only" %>
      <%= f.text_field :forum_name_cont, class: "form-control", placeholder: "Форум" %>
    </div>
    <div class="form-group">
      <%= f.label :marker_eq, "Метка ", class: "sr-only" %>
      <%= f.select :marker_eq, Question::MARKERS.map { |marker| [t(marker), marker] },{include_blank: true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :source_eq, "Иточник "%>
      <%= f.select :source_eq, [["TripAdvisor", Parser::TripAdvisor::SOURCE]],{include_blank: "LonleyPlanet"}, {class: "form-control"} %>
    </div>
    <p>
    <div class="form-group">
      <%= f.label :views_count_gteq, "Просмотров больше чем " %>
      <%= f.text_field :views_count_gteq, class: "form-control", placeholder: "5" %>
    </div>
    <p>
    <div class="form-group">
      <%= f.label :longest_answer_length_gteq, "Длина максимального ответа больше чем " %>
      <%= f.text_field :longest_answer_length_gteq, class: "form-control", placeholder: "1000" %>
    </div>
    <p>
    <div class="form-group">
      <%= f.label :max_strange_answer_length_gteq, "Длина максимального чужого ответа больше чем " %>
      <%= f.text_field :max_strange_answer_length_gteq, class: "form-control", placeholder: "1000" %>
    </div>
    <p>
    <div class="form-group">
      <%= f.label :date_gteq, "Дата публикации с "%>
      <%= f.date_field :date_gteq, class: "form-control" %>
      <%= f.label :date_lteq, "до " %>
      <%= f.date_field :date_lteq, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Поиск", class: "btn btn-info form-control", id: "search_btn" %>
    </div>
  <% end %>
</div>
<%= will_paginate @questions, renderer: BootstrapPagination::Rails %>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="col-md-1">Направление</th>
      <th class="col-md-1">Форум</th>
      <th class="col-md-3">Тема</th>
      <th class="col-md-6">Вопрос</th>
      <th class="col-md-2"><%= sort_link @search, :total_answers_weight, "Символов в ответе" %></th>
      <th class="col-md-2">Просмотров</th>
      <th class="col-md-2">Метка</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "question", collection: @questions, cache: true %>
  </tbody>
</table>
<%= will_paginate @questions, renderer: BootstrapPagination::Rails %>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/parse.html.erb
"OK"

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1>Вопрос</h1>
</div>

<dl id="question_<%= @question.id %>" class="dl-horizontal">
  <dt><strong>Тема:</strong></dt>
  <dd><%= @question.title %></dd>
  <dt><strong>Форум:</strong></dt>
  <dd><%= @question.forum.name %></dd>
  <dt><strong>Вопрос:</strong></dt>
  <dd><%= @question.content || "&nbsp;" %></dd>
  <dt><strong>Дата:</strong></dt>
  <dd><%= @question.date.try(:strftime, "%d.%m.%Y") || "&nbsp;" %></dd>
  <dt><strong>Просмотров:</strong></dt>
  <dd><%= @question.views_count %></dd>
  <dt><strong>Оригинал:</strong></dt>
  <dd><%= link_to @question.url, @question.url %></dd>
  <dt><strong>Количество символов в ответах:</strong></dt>
  <dd><%= @question.total_answers_weight || "" %></dd>
  <dt><strong>Маркер:</strong></dt>
  <dd><%= markers_for @question %></dd>
  <!-- <dd><%= t @question.marker %></dd> -->
</dl>
<h2>Ответы</h2>
<div class="checkbox">
  <label>
    <input type="checkbox" id="hide_owner" /> cкрыть ответы автора
  </label>
</div>
<%= will_paginate @answers, renderer: BootstrapPagination::Rails %>
<br>
<div class="container-fluid">
<% @answers.each do |answer| %>
  <div class="answer <%= 'author' if answer.author == @question.author %>">
    <%= answer.content %>
  </div>
<% end %>
</div>
<%= will_paginate @answers, renderer: BootstrapPagination::Rails %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              questions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_path(@question), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              question_path(@question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>